name: Flyteidl Verification Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'flyteidl/**'
  push:
    branches:
      - master
    paths:
      - 'flyteidl/**'
env:
  GO_VERSION: "1.19"
jobs:
  unpack-envvars:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.step.outputs.go-version }}
    steps:
      - id: step
        run: |
          echo "go-version=${{ env.GO_VERSION }}" >> $GITHUB_OUTPUT
  lint:
    name: Lint
    needs:
      - unpack-envvars
    strategy:
      fail-fast: false
    uses: ./.github/workflows/lint.yml
    with:
      component: flyteidl
      go-version: ${{ needs.unpack-envvars.outputs.go-version }}
  unit-tests:
    name: Unit Tests
    needs:
      - unpack-envvars
    uses: ./.github/workflows/unit-tests.yml
    with:
      component: flyteidl
      go-version: ${{ needs.unpack-envvars.outputs.go-version }}
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
  generate:
    name: Check Go Generate
    needs:
      - unpack-envvars
    strategy:
      fail-fast: false
    uses: ./.github/workflows/go_generate.yml
    with:
      component: flyteidl
      go-version: ${{ needs.unpack-envvars.outputs.go-version }}
